// Code generated by cmd/valid_env_vars. DO NOT EDIT.

package envvars

/*
This file contains a reference of all valid service environment variables.
*/

const (
	// APIServiceGrpcAPIServerURLEnvVarKey is the environment variable name to set to override `MCPServiceConfig.APIServiceConnection.GRPCAPIServerURL`.
	APIServiceGrpcAPIServerURLEnvVarKey = "ZHUZH_API_SERVICE_GRPC_API_SERVER_URL"

	// APIServiceHTTPAPIServerURLEnvVarKey is the environment variable name to set to override `MCPServiceConfig.APIServiceConnection.HTTPAPIServerURL`.
	APIServiceHTTPAPIServerURLEnvVarKey = "ZHUZH_API_SERVICE_HTTP_API_SERVER_URL"

	// APIServiceOauth2APIClientIDEnvVarKey is the environment variable name to set to override `MCPServiceConfig.APIServiceConnection.OAuth2APIClientID`.
	APIServiceOauth2APIClientIDEnvVarKey = "ZHUZH_API_SERVICE_OAUTH2_API_CLIENT_ID"

	// APIServiceOauth2APIClientSecretEnvVarKey is the environment variable name to set to override `MCPServiceConfig.APIServiceConnection.OAuth2APIClientSecret`.
	APIServiceOauth2APIClientSecretEnvVarKey = "ZHUZH_API_SERVICE_OAUTH2_API_CLIENT_SECRET"

	// APIServicePasswordEnvVarKey is the environment variable name to set to override `MCPServiceConfig.APIServiceConnection.Password`.
	APIServicePasswordEnvVarKey = "ZHUZH_API_SERVICE_PASSWORD"

	// APIServiceUsernameEnvVarKey is the environment variable name to set to override `MCPServiceConfig.APIServiceConnection.Username`.
	APIServiceUsernameEnvVarKey = "ZHUZH_API_SERVICE_USERNAME"

	// AnalyticsProxySourcesIosCircuitBreakerErrorRateEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.IOS.CircuitBreaker.ErrorRate`.
	AnalyticsProxySourcesIosCircuitBreakerErrorRateEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_IOS_CIRCUIT_BREAKER_ERROR_RATE"

	// AnalyticsProxySourcesIosCircuitBreakerMinimumSampleThresholdEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.IOS.CircuitBreaker.MinimumSampleThreshold`.
	AnalyticsProxySourcesIosCircuitBreakerMinimumSampleThresholdEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_IOS_CIRCUIT_BREAKER_MINIMUM_SAMPLE_THRESHOLD"

	// AnalyticsProxySourcesIosCircuitBreakerNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.IOS.CircuitBreaker.Name`.
	AnalyticsProxySourcesIosCircuitBreakerNameEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_IOS_CIRCUIT_BREAKER_NAME"

	// AnalyticsProxySourcesIosPosthogAPIKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.IOS.Posthog.APIKey`.
	AnalyticsProxySourcesIosPosthogAPIKeyEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_IOS_POSTHOG_API_KEY"

	// AnalyticsProxySourcesIosProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.IOS.Provider`.
	AnalyticsProxySourcesIosProviderEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_IOS_PROVIDER"

	// AnalyticsProxySourcesIosRudderstackAPIKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.IOS.Rudderstack.APIKey`.
	AnalyticsProxySourcesIosRudderstackAPIKeyEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_IOS_RUDDERSTACK_API_KEY"

	// AnalyticsProxySourcesIosRudderstackDataPlaneURLEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.IOS.Rudderstack.DataPlaneURL`.
	AnalyticsProxySourcesIosRudderstackDataPlaneURLEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_IOS_RUDDERSTACK_DATA_PLANE_URL"

	// AnalyticsProxySourcesIosSegmentAPITokenEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.IOS.Segment.APIToken`.
	AnalyticsProxySourcesIosSegmentAPITokenEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_IOS_SEGMENT_API_TOKEN"

	// AnalyticsProxySourcesWebCircuitBreakerErrorRateEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.Web.CircuitBreaker.ErrorRate`.
	AnalyticsProxySourcesWebCircuitBreakerErrorRateEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_WEB_CIRCUIT_BREAKER_ERROR_RATE"

	// AnalyticsProxySourcesWebCircuitBreakerMinimumSampleThresholdEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.Web.CircuitBreaker.MinimumSampleThreshold`.
	AnalyticsProxySourcesWebCircuitBreakerMinimumSampleThresholdEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_WEB_CIRCUIT_BREAKER_MINIMUM_SAMPLE_THRESHOLD"

	// AnalyticsProxySourcesWebCircuitBreakerNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.Web.CircuitBreaker.Name`.
	AnalyticsProxySourcesWebCircuitBreakerNameEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_WEB_CIRCUIT_BREAKER_NAME"

	// AnalyticsProxySourcesWebPosthogAPIKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.Web.Posthog.APIKey`.
	AnalyticsProxySourcesWebPosthogAPIKeyEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_WEB_POSTHOG_API_KEY"

	// AnalyticsProxySourcesWebProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.Web.Provider`.
	AnalyticsProxySourcesWebProviderEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_WEB_PROVIDER"

	// AnalyticsProxySourcesWebRudderstackAPIKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.Web.Rudderstack.APIKey`.
	AnalyticsProxySourcesWebRudderstackAPIKeyEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_WEB_RUDDERSTACK_API_KEY"

	// AnalyticsProxySourcesWebRudderstackDataPlaneURLEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.Web.Rudderstack.DataPlaneURL`.
	AnalyticsProxySourcesWebRudderstackDataPlaneURLEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_WEB_RUDDERSTACK_DATA_PLANE_URL"

	// AnalyticsProxySourcesWebSegmentAPITokenEnvVarKey is the environment variable name to set to override `APIServiceConfig.Analytics.ProxySources.Web.Segment.APIToken`.
	AnalyticsProxySourcesWebSegmentAPITokenEnvVarKey = "ZHUZH_ANALYTICS_PROXY_SOURCES_WEB_SEGMENT_API_TOKEN"

	// AuthDebugEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.Debug`.
	AuthDebugEnvVarKey = "ZHUZH_AUTH_DEBUG"

	// AuthEnableUserSignupEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.EnableUserSignup`.
	AuthEnableUserSignupEnvVarKey = "ZHUZH_AUTH_ENABLE_USER_SIGNUP"

	// AuthMinimumPasswordLengthEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.MinimumPasswordLength`.
	AuthMinimumPasswordLengthEnvVarKey = "ZHUZH_AUTH_MINIMUM_PASSWORD_LENGTH"

	// AuthMinimumUsernameLengthEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.MinimumUsernameLength`.
	AuthMinimumUsernameLengthEnvVarKey = "ZHUZH_AUTH_MINIMUM_USERNAME_LENGTH"

	// AuthPasskeyRpDisplayNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.Passkey.RPDisplayName`.
	AuthPasskeyRpDisplayNameEnvVarKey = "ZHUZH_AUTH_PASSKEY_RP_DISPLAY_NAME"

	// AuthPasskeyRpIDEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.Passkey.RPID`.
	AuthPasskeyRpIDEnvVarKey = "ZHUZH_AUTH_PASSKEY_RP_ID"

	// AuthPasskeyRpOriginsEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.Passkey.RPOrigins`.
	AuthPasskeyRpOriginsEnvVarKey = "ZHUZH_AUTH_PASSKEY_RP_ORIGINS"

	// AuthSessionStoreProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.SessionStore.Provider`.
	AuthSessionStoreProviderEnvVarKey = "ZHUZH_AUTH_SESSION_STORE_PROVIDER"

	// AuthSsoConfigGoogleSsoCallbackURLEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.SSO.Google.CallbackURL`.
	AuthSsoConfigGoogleSsoCallbackURLEnvVarKey = "ZHUZH_AUTH_SSO_CONFIG_GOOGLE_SSO_CALLBACK_URL"

	// AuthSsoConfigGoogleSsoClientIDEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.SSO.Google.ClientID`.
	AuthSsoConfigGoogleSsoClientIDEnvVarKey = "ZHUZH_AUTH_SSO_CONFIG_GOOGLE_SSO_CLIENT_ID"

	// AuthSsoConfigGoogleSsoClientSecretEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.SSO.Google.ClientSecret`.
	AuthSsoConfigGoogleSsoClientSecretEnvVarKey = "ZHUZH_AUTH_SSO_CONFIG_GOOGLE_SSO_CLIENT_SECRET"

	// AuthTokensAudienceEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.Tokens.Audience`.
	AuthTokensAudienceEnvVarKey = "ZHUZH_AUTH_TOKENS_AUDIENCE"

	// AuthTokensMaxAccessTokenLifetimeEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.Tokens.MaxAccessTokenLifetime`.
	AuthTokensMaxAccessTokenLifetimeEnvVarKey = "ZHUZH_AUTH_TOKENS_MAX_ACCESS_TOKEN_LIFETIME"

	// AuthTokensMaxRefreshTokenLifetimeEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.Tokens.MaxRefreshTokenLifetime`.
	AuthTokensMaxRefreshTokenLifetimeEnvVarKey = "ZHUZH_AUTH_TOKENS_MAX_REFRESH_TOKEN_LIFETIME"

	// AuthTokensProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.Tokens.Provider`.
	AuthTokensProviderEnvVarKey = "ZHUZH_AUTH_TOKENS_PROVIDER"

	// AuthTokensSigningKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Auth.Tokens.Base64EncodedSigningKey`.
	AuthTokensSigningKeyEnvVarKey = "ZHUZH_AUTH_TOKENS_SIGNING_KEY"

	// BaseURLEnvVarKey is the environment variable name to set to override `APIServiceConfigBaseURL`.
	BaseURLEnvVarKey = "ZHUZH_BASE_URL"

	// DatabaseConnMaxLifetimeEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.ConnMaxLifetime`.
	DatabaseConnMaxLifetimeEnvVarKey = "ZHUZH_DATABASE_CONN_MAX_LIFETIME"

	// DatabaseDebugEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.Debug`.
	DatabaseDebugEnvVarKey = "ZHUZH_DATABASE_DEBUG"

	// DatabaseEnableDatabaseMetricsEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.EnableDatabaseMetrics`.
	DatabaseEnableDatabaseMetricsEnvVarKey = "ZHUZH_DATABASE_ENABLE_DATABASE_METRICS"

	// DatabaseEncryptionProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.Encryption.Provider`.
	DatabaseEncryptionProviderEnvVarKey = "ZHUZH_DATABASE_ENCRYPTION_PROVIDER"

	// DatabaseLogQueriesEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.LogQueries`.
	DatabaseLogQueriesEnvVarKey = "ZHUZH_DATABASE_LOG_QUERIES"

	// DatabaseMaxIdleConnsEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.MaxIdleConns`.
	DatabaseMaxIdleConnsEnvVarKey = "ZHUZH_DATABASE_MAX_IDLE_CONNS"

	// DatabaseMaxOpenConnsEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.MaxOpenConns`.
	DatabaseMaxOpenConnsEnvVarKey = "ZHUZH_DATABASE_MAX_OPEN_CONNS"

	// DatabaseMaxPingAttemptsEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.MaxPingAttempts`.
	DatabaseMaxPingAttemptsEnvVarKey = "ZHUZH_DATABASE_MAX_PING_ATTEMPTS"

	// DatabaseOauth2TokenEncryptionKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.OAuth2TokenEncryptionKey`.
	DatabaseOauth2TokenEncryptionKeyEnvVarKey = "ZHUZH_DATABASE_OAUTH2_TOKEN_ENCRYPTION_KEY"

	// DatabasePingWaitPeriodEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.PingWaitPeriod`.
	DatabasePingWaitPeriodEnvVarKey = "ZHUZH_DATABASE_PING_WAIT_PERIOD"

	// DatabaseProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.Provider`.
	DatabaseProviderEnvVarKey = "ZHUZH_DATABASE_PROVIDER"

	// DatabaseReadConnectionDatabaseEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.ReadConnection.Database`.
	DatabaseReadConnectionDatabaseEnvVarKey = "ZHUZH_DATABASE_READ_CONNECTION_DATABASE"

	// DatabaseReadConnectionDisableSslEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.ReadConnection.DisableSSL`.
	DatabaseReadConnectionDisableSslEnvVarKey = "ZHUZH_DATABASE_READ_CONNECTION_DISABLE_SSL"

	// DatabaseReadConnectionHostEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.ReadConnection.Host`.
	DatabaseReadConnectionHostEnvVarKey = "ZHUZH_DATABASE_READ_CONNECTION_HOST"

	// DatabaseReadConnectionPasswordEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.ReadConnection.Password`.
	DatabaseReadConnectionPasswordEnvVarKey = "ZHUZH_DATABASE_READ_CONNECTION_PASSWORD"

	// DatabaseReadConnectionPortEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.ReadConnection.Port`.
	DatabaseReadConnectionPortEnvVarKey = "ZHUZH_DATABASE_READ_CONNECTION_PORT"

	// DatabaseReadConnectionUsernameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.ReadConnection.Username`.
	DatabaseReadConnectionUsernameEnvVarKey = "ZHUZH_DATABASE_READ_CONNECTION_USERNAME"

	// DatabaseRunMigrationsEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.RunMigrations`.
	DatabaseRunMigrationsEnvVarKey = "ZHUZH_DATABASE_RUN_MIGRATIONS"

	// DatabaseUserDeviceTokenEncryptionKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.UserDeviceTokenEncryptionKey`.
	DatabaseUserDeviceTokenEncryptionKeyEnvVarKey = "ZHUZH_DATABASE_USER_DEVICE_TOKEN_ENCRYPTION_KEY"

	// DatabaseWriteConnectionDatabaseEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.WriteConnection.Database`.
	DatabaseWriteConnectionDatabaseEnvVarKey = "ZHUZH_DATABASE_WRITE_CONNECTION_DATABASE"

	// DatabaseWriteConnectionDisableSslEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.WriteConnection.DisableSSL`.
	DatabaseWriteConnectionDisableSslEnvVarKey = "ZHUZH_DATABASE_WRITE_CONNECTION_DISABLE_SSL"

	// DatabaseWriteConnectionHostEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.WriteConnection.Host`.
	DatabaseWriteConnectionHostEnvVarKey = "ZHUZH_DATABASE_WRITE_CONNECTION_HOST"

	// DatabaseWriteConnectionPasswordEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.WriteConnection.Password`.
	DatabaseWriteConnectionPasswordEnvVarKey = "ZHUZH_DATABASE_WRITE_CONNECTION_PASSWORD"

	// DatabaseWriteConnectionPortEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.WriteConnection.Port`.
	DatabaseWriteConnectionPortEnvVarKey = "ZHUZH_DATABASE_WRITE_CONNECTION_PORT"

	// DatabaseWriteConnectionUsernameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Database.WriteConnection.Username`.
	DatabaseWriteConnectionUsernameEnvVarKey = "ZHUZH_DATABASE_WRITE_CONNECTION_USERNAME"

	// EmailBaseURLEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.BaseURL`.
	EmailBaseURLEnvVarKey = "ZHUZH_EMAIL_BASE_URL"

	// EmailCircuitBreakingErrorRateEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.CircuitBreaker.ErrorRate`.
	EmailCircuitBreakingErrorRateEnvVarKey = "ZHUZH_EMAIL_CIRCUIT_BREAKING_ERROR_RATE"

	// EmailCircuitBreakingMinimumSampleThresholdEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.CircuitBreaker.MinimumSampleThreshold`.
	EmailCircuitBreakingMinimumSampleThresholdEnvVarKey = "ZHUZH_EMAIL_CIRCUIT_BREAKING_MINIMUM_SAMPLE_THRESHOLD"

	// EmailCircuitBreakingNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.CircuitBreaker.Name`.
	EmailCircuitBreakingNameEnvVarKey = "ZHUZH_EMAIL_CIRCUIT_BREAKING_NAME"

	// EmailMailgunDomainEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.Mailgun.Domain`.
	EmailMailgunDomainEnvVarKey = "ZHUZH_EMAIL_MAILGUN_DOMAIN"

	// EmailMailgunPrivateAPIKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.Mailgun.PrivateAPIKey`.
	EmailMailgunPrivateAPIKeyEnvVarKey = "ZHUZH_EMAIL_MAILGUN_PRIVATE_API_KEY"

	// EmailMailjetAPIKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.Mailjet.APIKey`.
	EmailMailjetAPIKeyEnvVarKey = "ZHUZH_EMAIL_MAILJET_API_KEY"

	// EmailMailjetSecretKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.Mailjet.SecretKey`.
	EmailMailjetSecretKeyEnvVarKey = "ZHUZH_EMAIL_MAILJET_SECRET_KEY"

	// EmailOutboundInvitesEmailAddressEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.OutboundInvitesEmailAddress`.
	EmailOutboundInvitesEmailAddressEnvVarKey = "ZHUZH_EMAIL_OUTBOUND_INVITES_EMAIL_ADDRESS"

	// EmailPasswordResetCreationEmailAddressEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.PasswordResetCreationEmailAddress`.
	EmailPasswordResetCreationEmailAddressEnvVarKey = "ZHUZH_EMAIL_PASSWORD_RESET_CREATION_EMAIL_ADDRESS"

	// EmailPasswordResetRedemptionEmailAddressEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.PasswordResetRedemptionEmailAddress`.
	EmailPasswordResetRedemptionEmailAddressEnvVarKey = "ZHUZH_EMAIL_PASSWORD_RESET_REDEMPTION_EMAIL_ADDRESS"

	// EmailPostmarkBaseURLEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.Postmark.BaseURL`.
	EmailPostmarkBaseURLEnvVarKey = "ZHUZH_EMAIL_POSTMARK_BASE_URL"

	// EmailPostmarkServerTokenEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.Postmark.ServerToken`.
	EmailPostmarkServerTokenEnvVarKey = "ZHUZH_EMAIL_POSTMARK_SERVER_TOKEN"

	// EmailProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.Provider`.
	EmailProviderEnvVarKey = "ZHUZH_EMAIL_PROVIDER"

	// EmailResendAPITokenEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.Resend.APIToken`.
	EmailResendAPITokenEnvVarKey = "ZHUZH_EMAIL_RESEND_API_TOKEN"

	// EmailSendgridAPITokenEnvVarKey is the environment variable name to set to override `APIServiceConfig.Email.Sendgrid.APIToken`.
	EmailSendgridAPITokenEnvVarKey = "ZHUZH_EMAIL_SENDGRID_API_TOKEN"

	// EncodingContentTypeEnvVarKey is the environment variable name to set to override `APIServiceConfig.Encoding.ContentType`.
	EncodingContentTypeEnvVarKey = "ZHUZH_ENCODING_CONTENT_TYPE"

	// EventsConsumerProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Events.Consumer.Provider`.
	EventsConsumerProviderEnvVarKey = "ZHUZH_EVENTS_CONSUMER_PROVIDER"

	// EventsConsumerPubsubProjectIDEnvVarKey is the environment variable name to set to override `APIServiceConfig.Events.Consumer.PubSub.ProjectID`.
	EventsConsumerPubsubProjectIDEnvVarKey = "ZHUZH_EVENTS_CONSUMER_PUBSUB_PROJECT_ID"

	// EventsConsumerRedisPasswordEnvVarKey is the environment variable name to set to override `APIServiceConfig.Events.Consumer.Redis.Password`.
	EventsConsumerRedisPasswordEnvVarKey = "ZHUZH_EVENTS_CONSUMER_REDIS_PASSWORD"

	// EventsConsumerRedisQueueAddressesEnvVarKey is the environment variable name to set to override `APIServiceConfig.Events.Consumer.Redis.QueueAddresses`.
	EventsConsumerRedisQueueAddressesEnvVarKey = "ZHUZH_EVENTS_CONSUMER_REDIS_QUEUE_ADDRESSES"

	// EventsConsumerRedisUsernameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Events.Consumer.Redis.Username`.
	EventsConsumerRedisUsernameEnvVarKey = "ZHUZH_EVENTS_CONSUMER_REDIS_USERNAME"

	// EventsConsumerSqsQueueAddressEnvVarKey is the environment variable name to set to override `APIServiceConfig.Events.Consumer.SQS.QueueAddress`.
	EventsConsumerSqsQueueAddressEnvVarKey = "ZHUZH_EVENTS_CONSUMER_SQS_QUEUE_ADDRESS"

	// EventsPublisherProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Events.Publisher.Provider`.
	EventsPublisherProviderEnvVarKey = "ZHUZH_EVENTS_PUBLISHER_PROVIDER"

	// EventsPublisherPubsubProjectIDEnvVarKey is the environment variable name to set to override `APIServiceConfig.Events.Publisher.PubSub.ProjectID`.
	EventsPublisherPubsubProjectIDEnvVarKey = "ZHUZH_EVENTS_PUBLISHER_PUBSUB_PROJECT_ID"

	// EventsPublisherRedisPasswordEnvVarKey is the environment variable name to set to override `APIServiceConfig.Events.Publisher.Redis.Password`.
	EventsPublisherRedisPasswordEnvVarKey = "ZHUZH_EVENTS_PUBLISHER_REDIS_PASSWORD"

	// EventsPublisherRedisQueueAddressesEnvVarKey is the environment variable name to set to override `APIServiceConfig.Events.Publisher.Redis.QueueAddresses`.
	EventsPublisherRedisQueueAddressesEnvVarKey = "ZHUZH_EVENTS_PUBLISHER_REDIS_QUEUE_ADDRESSES"

	// EventsPublisherRedisUsernameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Events.Publisher.Redis.Username`.
	EventsPublisherRedisUsernameEnvVarKey = "ZHUZH_EVENTS_PUBLISHER_REDIS_USERNAME"

	// EventsPublisherSqsQueueAddressEnvVarKey is the environment variable name to set to override `APIServiceConfig.Events.Publisher.SQS.QueueAddress`.
	EventsPublisherSqsQueueAddressEnvVarKey = "ZHUZH_EVENTS_PUBLISHER_SQS_QUEUE_ADDRESS"

	// FeatureFlagsCircuitBreakingErrorRateEnvVarKey is the environment variable name to set to override `APIServiceConfig.FeatureFlags.CircuitBreaker.ErrorRate`.
	FeatureFlagsCircuitBreakingErrorRateEnvVarKey = "ZHUZH_FEATURE_FLAGS_CIRCUIT_BREAKING_ERROR_RATE"

	// FeatureFlagsCircuitBreakingMinimumSampleThresholdEnvVarKey is the environment variable name to set to override `APIServiceConfig.FeatureFlags.CircuitBreaker.MinimumSampleThreshold`.
	FeatureFlagsCircuitBreakingMinimumSampleThresholdEnvVarKey = "ZHUZH_FEATURE_FLAGS_CIRCUIT_BREAKING_MINIMUM_SAMPLE_THRESHOLD"

	// FeatureFlagsCircuitBreakingNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.FeatureFlags.CircuitBreaker.Name`.
	FeatureFlagsCircuitBreakingNameEnvVarKey = "ZHUZH_FEATURE_FLAGS_CIRCUIT_BREAKING_NAME"

	// FeatureFlagsLaunchDarklycircuitBreakingErrorRateEnvVarKey is the environment variable name to set to override `APIServiceConfig.FeatureFlags.LaunchDarkly.CircuitBreakerConfig.ErrorRate`.
	FeatureFlagsLaunchDarklycircuitBreakingErrorRateEnvVarKey = "ZHUZH_FEATURE_FLAGS_LAUNCH_DARKLYCIRCUIT_BREAKING_ERROR_RATE"

	// FeatureFlagsLaunchDarklycircuitBreakingMinimumSampleThresholdEnvVarKey is the environment variable name to set to override `APIServiceConfig.FeatureFlags.LaunchDarkly.CircuitBreakerConfig.MinimumSampleThreshold`.
	FeatureFlagsLaunchDarklycircuitBreakingMinimumSampleThresholdEnvVarKey = "ZHUZH_FEATURE_FLAGS_LAUNCH_DARKLYCIRCUIT_BREAKING_MINIMUM_SAMPLE_THRESHOLD"

	// FeatureFlagsLaunchDarklycircuitBreakingNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.FeatureFlags.LaunchDarkly.CircuitBreakerConfig.Name`.
	FeatureFlagsLaunchDarklycircuitBreakingNameEnvVarKey = "ZHUZH_FEATURE_FLAGS_LAUNCH_DARKLYCIRCUIT_BREAKING_NAME"

	// FeatureFlagsLaunchDarklyinitTimeoutEnvVarKey is the environment variable name to set to override `APIServiceConfig.FeatureFlags.LaunchDarkly.InitTimeout`.
	FeatureFlagsLaunchDarklyinitTimeoutEnvVarKey = "ZHUZH_FEATURE_FLAGS_LAUNCH_DARKLYINIT_TIMEOUT"

	// FeatureFlagsLaunchDarklysdkKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.FeatureFlags.LaunchDarkly.SDKKey`.
	FeatureFlagsLaunchDarklysdkKeyEnvVarKey = "ZHUZH_FEATURE_FLAGS_LAUNCH_DARKLYSDK_KEY"

	// FeatureFlagsPosthogCircuitBreakingErrorRateEnvVarKey is the environment variable name to set to override `APIServiceConfig.FeatureFlags.PostHog.CircuitBreakerConfig.ErrorRate`.
	FeatureFlagsPosthogCircuitBreakingErrorRateEnvVarKey = "ZHUZH_FEATURE_FLAGS_POSTHOG_CIRCUIT_BREAKING_ERROR_RATE"

	// FeatureFlagsPosthogCircuitBreakingMinimumSampleThresholdEnvVarKey is the environment variable name to set to override `APIServiceConfig.FeatureFlags.PostHog.CircuitBreakerConfig.MinimumSampleThreshold`.
	FeatureFlagsPosthogCircuitBreakingMinimumSampleThresholdEnvVarKey = "ZHUZH_FEATURE_FLAGS_POSTHOG_CIRCUIT_BREAKING_MINIMUM_SAMPLE_THRESHOLD"

	// FeatureFlagsPosthogCircuitBreakingNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.FeatureFlags.PostHog.CircuitBreakerConfig.Name`.
	FeatureFlagsPosthogCircuitBreakingNameEnvVarKey = "ZHUZH_FEATURE_FLAGS_POSTHOG_CIRCUIT_BREAKING_NAME"

	// FeatureFlagsPosthogPersonalAPIKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.FeatureFlags.PostHog.PersonalAPIKey`.
	FeatureFlagsPosthogPersonalAPIKeyEnvVarKey = "ZHUZH_FEATURE_FLAGS_POSTHOG_PERSONAL_API_KEY"

	// FeatureFlagsPosthogProjectAPIKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.FeatureFlags.PostHog.ProjectAPIKey`.
	FeatureFlagsPosthogProjectAPIKeyEnvVarKey = "ZHUZH_FEATURE_FLAGS_POSTHOG_PROJECT_API_KEY"

	// FeatureFlagsProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.FeatureFlags.Provider`.
	FeatureFlagsProviderEnvVarKey = "ZHUZH_FEATURE_FLAGS_PROVIDER"

	// GrpcPortEnvVarKey is the environment variable name to set to override `APIServiceConfig.GRPCServer.Port`.
	GrpcPortEnvVarKey = "ZHUZH_GRPC_PORT"

	// GrpcTLSCertificateFilepathEnvVarKey is the environment variable name to set to override `APIServiceConfig.GRPCServer.HTTPSCertificateFile`.
	GrpcTLSCertificateFilepathEnvVarKey = "ZHUZH_GRPC_TLS_CERTIFICATE_FILEPATH"

	// GrpcTLSCertificateKeyFilepathEnvVarKey is the environment variable name to set to override `APIServiceConfig.GRPCServer.TLSCertificateKeyFile`.
	GrpcTLSCertificateKeyFilepathEnvVarKey = "ZHUZH_GRPC_TLS_CERTIFICATE_KEY_FILEPATH"

	// HTTPClientEnableTracingEnvVarKey is the environment variable name to set to override `APIServiceConfig.HTTPClient.EnableTracing`.
	HTTPClientEnableTracingEnvVarKey = "ZHUZH_HTTP_CLIENT_ENABLE_TRACING"

	// HTTPClientMaxIdleConnsEnvVarKey is the environment variable name to set to override `APIServiceConfig.HTTPClient.MaxIdleConns`.
	HTTPClientMaxIdleConnsEnvVarKey = "ZHUZH_HTTP_CLIENT_MAX_IDLE_CONNS"

	// HTTPClientMaxIdleConnsPerHostEnvVarKey is the environment variable name to set to override `APIServiceConfig.HTTPClient.MaxIdleConnsPerHost`.
	HTTPClientMaxIdleConnsPerHostEnvVarKey = "ZHUZH_HTTP_CLIENT_MAX_IDLE_CONNS_PER_HOST"

	// HTTPClientTimeoutEnvVarKey is the environment variable name to set to override `APIServiceConfig.HTTPClient.Timeout`.
	HTTPClientTimeoutEnvVarKey = "ZHUZH_HTTP_CLIENT_TIMEOUT"

	// HTTPDebugEnvVarKey is the environment variable name to set to override `APIServiceConfig.HTTPServer.Debug`.
	HTTPDebugEnvVarKey = "ZHUZH_HTTP_DEBUG"

	// HTTPPortEnvVarKey is the environment variable name to set to override `APIServiceConfig.HTTPServer.Port`.
	HTTPPortEnvVarKey = "ZHUZH_HTTP_PORT"

	// HTTPSslCertificateFilepathEnvVarKey is the environment variable name to set to override `APIServiceConfig.HTTPServer.SSLCertificateFile`.
	HTTPSslCertificateFilepathEnvVarKey = "ZHUZH_HTTP_SSL_CERTIFICATE_FILEPATH"

	// HTTPSslCertificateKeyFilepathEnvVarKey is the environment variable name to set to override `APIServiceConfig.HTTPServer.SSLCertificateKeyFile`.
	HTTPSslCertificateKeyFilepathEnvVarKey = "ZHUZH_HTTP_SSL_CERTIFICATE_KEY_FILEPATH"

	// HTTPStartupDeadlineEnvVarKey is the environment variable name to set to override `APIServiceConfig.HTTPServer.StartupDeadline`.
	HTTPStartupDeadlineEnvVarKey = "ZHUZH_HTTP_STARTUP_DEADLINE"

	// MetaDebugEnvVarKey is the environment variable name to set to override `APIServiceConfig.Meta.Debug`.
	MetaDebugEnvVarKey = "ZHUZH_META_DEBUG"

	// MetaRunModeEnvVarKey is the environment variable name to set to override `APIServiceConfig.Meta.RunMode`.
	MetaRunModeEnvVarKey = "ZHUZH_META_RUN_MODE"

	// ObservabilityLoggingLevelEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Logging.Level`.
	ObservabilityLoggingLevelEnvVarKey = "ZHUZH_OBSERVABILITY_LOGGING_LEVEL"

	// ObservabilityLoggingOtelSlogEndpointURLEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Logging.OtelSlog.CollectorEndpoint`.
	ObservabilityLoggingOtelSlogEndpointURLEnvVarKey = "ZHUZH_OBSERVABILITY_LOGGING_OTEL_SLOG_ENDPOINT_URL"

	// ObservabilityLoggingOtelSlogInsecureEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Logging.OtelSlog.Insecure`.
	ObservabilityLoggingOtelSlogInsecureEnvVarKey = "ZHUZH_OBSERVABILITY_LOGGING_OTEL_SLOG_INSECURE"

	// ObservabilityLoggingOtelSlogTimeoutEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Logging.OtelSlog.Timeout`.
	ObservabilityLoggingOtelSlogTimeoutEnvVarKey = "ZHUZH_OBSERVABILITY_LOGGING_OTEL_SLOG_TIMEOUT"

	// ObservabilityLoggingProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Logging.Provider`.
	ObservabilityLoggingProviderEnvVarKey = "ZHUZH_OBSERVABILITY_LOGGING_PROVIDER"

	// ObservabilityLoggingServiceNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Logging.ServiceName`.
	ObservabilityLoggingServiceNameEnvVarKey = "ZHUZH_OBSERVABILITY_LOGGING_SERVICE_NAME"

	// ObservabilityMetricsOtelCollectionIntervalEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Metrics.Otel.CollectionInterval`.
	ObservabilityMetricsOtelCollectionIntervalEnvVarKey = "ZHUZH_OBSERVABILITY_METRICS_OTEL_COLLECTION_INTERVAL"

	// ObservabilityMetricsOtelCollectorEndpointEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Metrics.Otel.CollectorEndpoint`.
	ObservabilityMetricsOtelCollectorEndpointEnvVarKey = "ZHUZH_OBSERVABILITY_METRICS_OTEL_COLLECTOR_ENDPOINT"

	// ObservabilityMetricsOtelEnableHostMetricsEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Metrics.Otel.EnableHostMetrics`.
	ObservabilityMetricsOtelEnableHostMetricsEnvVarKey = "ZHUZH_OBSERVABILITY_METRICS_OTEL_ENABLE_HOST_METRICS"

	// ObservabilityMetricsOtelEnableRuntimeMetricsEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Metrics.Otel.EnableRuntimeMetrics`.
	ObservabilityMetricsOtelEnableRuntimeMetricsEnvVarKey = "ZHUZH_OBSERVABILITY_METRICS_OTEL_ENABLE_RUNTIME_METRICS"

	// ObservabilityMetricsOtelInsecureEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Metrics.Otel.Insecure`.
	ObservabilityMetricsOtelInsecureEnvVarKey = "ZHUZH_OBSERVABILITY_METRICS_OTEL_INSECURE"

	// ObservabilityMetricsProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Metrics.Provider`.
	ObservabilityMetricsProviderEnvVarKey = "ZHUZH_OBSERVABILITY_METRICS_PROVIDER"

	// ObservabilityMetricsServiceNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Metrics.ServiceName`.
	ObservabilityMetricsServiceNameEnvVarKey = "ZHUZH_OBSERVABILITY_METRICS_SERVICE_NAME"

	// ObservabilityProfilingPprofEnableBlockProfileEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Profiling.Pprof.EnableBlockProfile`.
	ObservabilityProfilingPprofEnableBlockProfileEnvVarKey = "ZHUZH_OBSERVABILITY_PROFILING_PPROF_ENABLE_BLOCK_PROFILE"

	// ObservabilityProfilingPprofEnableMutexProfileEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Profiling.Pprof.EnableMutexProfile`.
	ObservabilityProfilingPprofEnableMutexProfileEnvVarKey = "ZHUZH_OBSERVABILITY_PROFILING_PPROF_ENABLE_MUTEX_PROFILE"

	// ObservabilityProfilingPprofPortEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Profiling.Pprof.Port`.
	ObservabilityProfilingPprofPortEnvVarKey = "ZHUZH_OBSERVABILITY_PROFILING_PPROF_PORT"

	// ObservabilityProfilingProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Profiling.Provider`.
	ObservabilityProfilingProviderEnvVarKey = "ZHUZH_OBSERVABILITY_PROFILING_PROVIDER"

	// ObservabilityProfilingPyroscopeBasicAuthPasswordEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Profiling.Pyroscope.BasicAuthPassword`.
	ObservabilityProfilingPyroscopeBasicAuthPasswordEnvVarKey = "ZHUZH_OBSERVABILITY_PROFILING_PYROSCOPE_BASIC_AUTH_PASSWORD"

	// ObservabilityProfilingPyroscopeBasicAuthUserEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Profiling.Pyroscope.BasicAuthUser`.
	ObservabilityProfilingPyroscopeBasicAuthUserEnvVarKey = "ZHUZH_OBSERVABILITY_PROFILING_PYROSCOPE_BASIC_AUTH_USER"

	// ObservabilityProfilingPyroscopeEnableBlockProfileEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Profiling.Pyroscope.EnableBlockProfile`.
	ObservabilityProfilingPyroscopeEnableBlockProfileEnvVarKey = "ZHUZH_OBSERVABILITY_PROFILING_PYROSCOPE_ENABLE_BLOCK_PROFILE"

	// ObservabilityProfilingPyroscopeEnableMutexProfileEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Profiling.Pyroscope.EnableMutexProfile`.
	ObservabilityProfilingPyroscopeEnableMutexProfileEnvVarKey = "ZHUZH_OBSERVABILITY_PROFILING_PYROSCOPE_ENABLE_MUTEX_PROFILE"

	// ObservabilityProfilingPyroscopeEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Profiling.Pyroscope.Tags`.
	ObservabilityProfilingPyroscopeEnvVarKey = "ZHUZH_OBSERVABILITY_PROFILING_PYROSCOPE_-"

	// ObservabilityProfilingPyroscopeInsecureEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Profiling.Pyroscope.Insecure`.
	ObservabilityProfilingPyroscopeInsecureEnvVarKey = "ZHUZH_OBSERVABILITY_PROFILING_PYROSCOPE_INSECURE"

	// ObservabilityProfilingPyroscopeServerAddressEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Profiling.Pyroscope.ServerAddress`.
	ObservabilityProfilingPyroscopeServerAddressEnvVarKey = "ZHUZH_OBSERVABILITY_PROFILING_PYROSCOPE_SERVER_ADDRESS"

	// ObservabilityProfilingPyroscopeUploadRateEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Profiling.Pyroscope.UploadRate`.
	ObservabilityProfilingPyroscopeUploadRateEnvVarKey = "ZHUZH_OBSERVABILITY_PROFILING_PYROSCOPE_UPLOAD_RATE"

	// ObservabilityProfilingServiceNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Profiling.ServiceName`.
	ObservabilityProfilingServiceNameEnvVarKey = "ZHUZH_OBSERVABILITY_PROFILING_SERVICE_NAME"

	// ObservabilityTracingCloudtraceGoogleCloudTraceProjectIDEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Tracing.CloudTrace.ProjectID`.
	ObservabilityTracingCloudtraceGoogleCloudTraceProjectIDEnvVarKey = "ZHUZH_OBSERVABILITY_TRACING_CLOUDTRACE_GOOGLE_CLOUD_TRACE_PROJECT_ID"

	// ObservabilityTracingOtelgrpcCollectorEndpointEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Tracing.Otel.CollectorEndpoint`.
	ObservabilityTracingOtelgrpcCollectorEndpointEnvVarKey = "ZHUZH_OBSERVABILITY_TRACING_OTELGRPC_COLLECTOR_ENDPOINT"

	// ObservabilityTracingOtelgrpcInsecureEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Tracing.Otel.Insecure`.
	ObservabilityTracingOtelgrpcInsecureEnvVarKey = "ZHUZH_OBSERVABILITY_TRACING_OTELGRPC_INSECURE"

	// ObservabilityTracingTracingProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Tracing.Provider`.
	ObservabilityTracingTracingProviderEnvVarKey = "ZHUZH_OBSERVABILITY_TRACING_TRACING_PROVIDER"

	// ObservabilityTracingTracingServiceNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Tracing.ServiceName`.
	ObservabilityTracingTracingServiceNameEnvVarKey = "ZHUZH_OBSERVABILITY_TRACING_TRACING_SERVICE_NAME"

	// ObservabilityTracingTracingSpanCollectionProbabilityEnvVarKey is the environment variable name to set to override `APIServiceConfig.Observability.Tracing.SpanCollectionProbability`.
	ObservabilityTracingTracingSpanCollectionProbabilityEnvVarKey = "ZHUZH_OBSERVABILITY_TRACING_TRACING_SPAN_COLLECTION_PROBABILITY"

	// PushNotificationsApnsAuthKeyPathEnvVarKey is the environment variable name to set to override `APIServiceConfig.PushNotifications.APNs.AuthKeyPath`.
	PushNotificationsApnsAuthKeyPathEnvVarKey = "ZHUZH_PUSH_NOTIFICATIONS_APNS_AUTH_KEY_PATH"

	// PushNotificationsApnsBundleIDEnvVarKey is the environment variable name to set to override `APIServiceConfig.PushNotifications.APNs.BundleID`.
	PushNotificationsApnsBundleIDEnvVarKey = "ZHUZH_PUSH_NOTIFICATIONS_APNS_BUNDLE_ID"

	// PushNotificationsApnsKeyIDEnvVarKey is the environment variable name to set to override `APIServiceConfig.PushNotifications.APNs.KeyID`.
	PushNotificationsApnsKeyIDEnvVarKey = "ZHUZH_PUSH_NOTIFICATIONS_APNS_KEY_ID"

	// PushNotificationsApnsProductionEnvVarKey is the environment variable name to set to override `APIServiceConfig.PushNotifications.APNs.Production`.
	PushNotificationsApnsProductionEnvVarKey = "ZHUZH_PUSH_NOTIFICATIONS_APNS_PRODUCTION"

	// PushNotificationsApnsTeamIDEnvVarKey is the environment variable name to set to override `APIServiceConfig.PushNotifications.APNs.TeamID`.
	PushNotificationsApnsTeamIDEnvVarKey = "ZHUZH_PUSH_NOTIFICATIONS_APNS_TEAM_ID"

	// PushNotificationsFcmCredentialsPathEnvVarKey is the environment variable name to set to override `APIServiceConfig.PushNotifications.FCM.CredentialsPath`.
	PushNotificationsFcmCredentialsPathEnvVarKey = "ZHUZH_PUSH_NOTIFICATIONS_FCM_CREDENTIALS_PATH"

	// PushNotificationsProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.PushNotifications.Provider`.
	PushNotificationsProviderEnvVarKey = "ZHUZH_PUSH_NOTIFICATIONS_PROVIDER"

	// QueuesDataChangesTopicNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Queues.DataChangesTopicName`.
	QueuesDataChangesTopicNameEnvVarKey = "ZHUZH_QUEUES_DATA_CHANGES_TOPIC_NAME"

	// QueuesMobileNotificationsTopicNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Queues.MobileNotificationsTopicName`.
	QueuesMobileNotificationsTopicNameEnvVarKey = "ZHUZH_QUEUES_MOBILE_NOTIFICATIONS_TOPIC_NAME"

	// QueuesOutboundEmailsTopicNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Queues.OutboundEmailsTopicName`.
	QueuesOutboundEmailsTopicNameEnvVarKey = "ZHUZH_QUEUES_OUTBOUND_EMAILS_TOPIC_NAME"

	// QueuesSearchIndexRequestsTopicNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Queues.SearchIndexRequestsTopicName`.
	QueuesSearchIndexRequestsTopicNameEnvVarKey = "ZHUZH_QUEUES_SEARCH_INDEX_REQUESTS_TOPIC_NAME"

	// QueuesUserDataAggregationTopicNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Queues.UserDataAggregationTopicName`.
	QueuesUserDataAggregationTopicNameEnvVarKey = "ZHUZH_QUEUES_USER_DATA_AGGREGATION_TOPIC_NAME"

	// QueuesWebhookExecutionRequestsTopicNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Queues.WebhookExecutionRequestsTopicName`.
	QueuesWebhookExecutionRequestsTopicNameEnvVarKey = "ZHUZH_QUEUES_WEBHOOK_EXECUTION_REQUESTS_TOPIC_NAME"

	// RecipientEmailAddressEnvVarKey is the environment variable name to set to override `EmailDeliverabilityTestConfigRecipientEmailAddress`.
	RecipientEmailAddressEnvVarKey = "ZHUZH_RECIPIENT_EMAIL_ADDRESS"

	// RoutingChiEnableCorsForLocalhostEnvVarKey is the environment variable name to set to override `APIServiceConfig.Routing.Chi.EnableCORSForLocalhost`.
	RoutingChiEnableCorsForLocalhostEnvVarKey = "ZHUZH_ROUTING_CHI_ENABLE_CORS_FOR_LOCALHOST"

	// RoutingChiServiceNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Routing.Chi.ServiceName`.
	RoutingChiServiceNameEnvVarKey = "ZHUZH_ROUTING_CHI_SERVICE_NAME"

	// RoutingChiSilenceRouteLoggingEnvVarKey is the environment variable name to set to override `APIServiceConfig.Routing.Chi.SilenceRouteLogging`.
	RoutingChiSilenceRouteLoggingEnvVarKey = "ZHUZH_ROUTING_CHI_SILENCE_ROUTE_LOGGING"

	// RoutingChiValidDomainsEnvVarKey is the environment variable name to set to override `APIServiceConfig.Routing.Chi.ValidDomains`.
	RoutingChiValidDomainsEnvVarKey = "ZHUZH_ROUTING_CHI_VALID_DOMAINS"

	// RoutingProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Routing.Provider`.
	RoutingProviderEnvVarKey = "ZHUZH_ROUTING_PROVIDER"

	// SearchAlgoliaAPIKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.TextSearch.Algolia.APIKey`.
	SearchAlgoliaAPIKeyEnvVarKey = "ZHUZH_SEARCH_ALGOLIA_API_KEY"

	// SearchAlgoliaAppIDEnvVarKey is the environment variable name to set to override `APIServiceConfig.TextSearch.Algolia.AppID`.
	SearchAlgoliaAppIDEnvVarKey = "ZHUZH_SEARCH_ALGOLIA_APP_ID"

	// SearchAlgoliaTimeoutEnvVarKey is the environment variable name to set to override `APIServiceConfig.TextSearch.Algolia.Timeout`.
	SearchAlgoliaTimeoutEnvVarKey = "ZHUZH_SEARCH_ALGOLIA_TIMEOUT"

	// SearchCircuitBreakerErrorRateEnvVarKey is the environment variable name to set to override `APIServiceConfig.TextSearch.CircuitBreaker.ErrorRate`.
	SearchCircuitBreakerErrorRateEnvVarKey = "ZHUZH_SEARCH_CIRCUIT_BREAKER_ERROR_RATE"

	// SearchCircuitBreakerMinimumSampleThresholdEnvVarKey is the environment variable name to set to override `APIServiceConfig.TextSearch.CircuitBreaker.MinimumSampleThreshold`.
	SearchCircuitBreakerMinimumSampleThresholdEnvVarKey = "ZHUZH_SEARCH_CIRCUIT_BREAKER_MINIMUM_SAMPLE_THRESHOLD"

	// SearchCircuitBreakerNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.TextSearch.CircuitBreaker.Name`.
	SearchCircuitBreakerNameEnvVarKey = "ZHUZH_SEARCH_CIRCUIT_BREAKER_NAME"

	// SearchElasticsearchAddressEnvVarKey is the environment variable name to set to override `APIServiceConfig.TextSearch.Elasticsearch.Address`.
	SearchElasticsearchAddressEnvVarKey = "ZHUZH_SEARCH_ELASTICSEARCH_ADDRESS"

	// SearchElasticsearchCaCertEnvVarKey is the environment variable name to set to override `APIServiceConfig.TextSearch.Elasticsearch.CACert`.
	SearchElasticsearchCaCertEnvVarKey = "ZHUZH_SEARCH_ELASTICSEARCH_CA_CERT"

	// SearchElasticsearchIndexOperationTimeoutEnvVarKey is the environment variable name to set to override `APIServiceConfig.TextSearch.Elasticsearch.IndexOperationTimeout`.
	SearchElasticsearchIndexOperationTimeoutEnvVarKey = "ZHUZH_SEARCH_ELASTICSEARCH_INDEX_OPERATION_TIMEOUT"

	// SearchElasticsearchPasswordEnvVarKey is the environment variable name to set to override `APIServiceConfig.TextSearch.Elasticsearch.Password`.
	SearchElasticsearchPasswordEnvVarKey = "ZHUZH_SEARCH_ELASTICSEARCH_PASSWORD"

	// SearchElasticsearchUsernameEnvVarKey is the environment variable name to set to override `APIServiceConfig.TextSearch.Elasticsearch.Username`.
	SearchElasticsearchUsernameEnvVarKey = "ZHUZH_SEARCH_ELASTICSEARCH_USERNAME"

	// SearchProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.TextSearch.Provider`.
	SearchProviderEnvVarKey = "ZHUZH_SEARCH_PROVIDER"

	// ServiceAuthDebugEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.Debug`.
	ServiceAuthDebugEnvVarKey = "ZHUZH_SERVICE_AUTH_DEBUG"

	// ServiceAuthEnableUserSignupEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.EnableUserSignup`.
	ServiceAuthEnableUserSignupEnvVarKey = "ZHUZH_SERVICE_AUTH_ENABLE_USER_SIGNUP"

	// ServiceAuthJwtLifetimeEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.TokenLifetime`.
	ServiceAuthJwtLifetimeEnvVarKey = "ZHUZH_SERVICE_AUTH_JWT_LIFETIME"

	// ServiceAuthMinimumPasswordLengthEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.MinimumPasswordLength`.
	ServiceAuthMinimumPasswordLengthEnvVarKey = "ZHUZH_SERVICE_AUTH_MINIMUM_PASSWORD_LENGTH"

	// ServiceAuthMinimumUsernameLengthEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.MinimumUsernameLength`.
	ServiceAuthMinimumUsernameLengthEnvVarKey = "ZHUZH_SERVICE_AUTH_MINIMUM_USERNAME_LENGTH"

	// ServiceAuthOauth2AccessTokenLifespanEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.OAuth2.AccessTokenLifespan`.
	ServiceAuthOauth2AccessTokenLifespanEnvVarKey = "ZHUZH_SERVICE_AUTH_OAUTH2ACCESS_TOKEN_LIFESPAN"

	// ServiceAuthOauth2DebugEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.OAuth2.Debug`.
	ServiceAuthOauth2DebugEnvVarKey = "ZHUZH_SERVICE_AUTH_OAUTH2DEBUG"

	// ServiceAuthOauth2DomainEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.OAuth2.Domain`.
	ServiceAuthOauth2DomainEnvVarKey = "ZHUZH_SERVICE_AUTH_OAUTH2DOMAIN"

	// ServiceAuthOauth2RefreshTokenLifespanEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.OAuth2.RefreshTokenLifespan`.
	ServiceAuthOauth2RefreshTokenLifespanEnvVarKey = "ZHUZH_SERVICE_AUTH_OAUTH2REFRESH_TOKEN_LIFESPAN"

	// ServiceAuthSsoConfigGoogleCallbackURLEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.SSO.Google.CallbackURL`.
	ServiceAuthSsoConfigGoogleCallbackURLEnvVarKey = "ZHUZH_SERVICE_AUTH_SSO_CONFIG_GOOGLE_CALLBACK_URL"

	// ServiceAuthSsoConfigGoogleClientIDEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.SSO.Google.ClientID`.
	ServiceAuthSsoConfigGoogleClientIDEnvVarKey = "ZHUZH_SERVICE_AUTH_SSO_CONFIG_GOOGLE_CLIENT_ID"

	// ServiceAuthSsoConfigGoogleClientSecretEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.SSO.Google.ClientSecret`.
	ServiceAuthSsoConfigGoogleClientSecretEnvVarKey = "ZHUZH_SERVICE_AUTH_SSO_CONFIG_GOOGLE_CLIENT_SECRET"

	// ServiceAuthTokensAudienceEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.Tokens.Audience`.
	ServiceAuthTokensAudienceEnvVarKey = "ZHUZH_SERVICE_AUTH_TOKENS_AUDIENCE"

	// ServiceAuthTokensMaxAccessTokenLifetimeEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.Tokens.MaxAccessTokenLifetime`.
	ServiceAuthTokensMaxAccessTokenLifetimeEnvVarKey = "ZHUZH_SERVICE_AUTH_TOKENS_MAX_ACCESS_TOKEN_LIFETIME"

	// ServiceAuthTokensMaxRefreshTokenLifetimeEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.Tokens.MaxRefreshTokenLifetime`.
	ServiceAuthTokensMaxRefreshTokenLifetimeEnvVarKey = "ZHUZH_SERVICE_AUTH_TOKENS_MAX_REFRESH_TOKEN_LIFETIME"

	// ServiceAuthTokensProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.Tokens.Provider`.
	ServiceAuthTokensProviderEnvVarKey = "ZHUZH_SERVICE_AUTH_TOKENS_PROVIDER"

	// ServiceAuthTokensSigningKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Auth.Tokens.Base64EncodedSigningKey`.
	ServiceAuthTokensSigningKeyEnvVarKey = "ZHUZH_SERVICE_AUTH_TOKENS_SIGNING_KEY"

	// ServiceDataPrivacyUploadsDebugEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.DataPrivacy.Uploads.Debug`.
	ServiceDataPrivacyUploadsDebugEnvVarKey = "ZHUZH_SERVICE_DATA_PRIVACY_UPLOADS_DEBUG"

	// ServiceDataPrivacyUploadsStorageBucketNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.DataPrivacy.Uploads.Storage.BucketName`.
	ServiceDataPrivacyUploadsStorageBucketNameEnvVarKey = "ZHUZH_SERVICE_DATA_PRIVACY_UPLOADS_STORAGE_BUCKET_NAME"

	// ServiceDataPrivacyUploadsStorageBucketPrefixEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.DataPrivacy.Uploads.Storage.BucketPrefix`.
	ServiceDataPrivacyUploadsStorageBucketPrefixEnvVarKey = "ZHUZH_SERVICE_DATA_PRIVACY_UPLOADS_STORAGE_BUCKET_PREFIX"

	// ServiceDataPrivacyUploadsStorageFilesystemRootDirectoryEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.DataPrivacy.Uploads.Storage.FilesystemConfig.RootDirectory`.
	ServiceDataPrivacyUploadsStorageFilesystemRootDirectoryEnvVarKey = "ZHUZH_SERVICE_DATA_PRIVACY_UPLOADS_STORAGE_FILESYSTEM_ROOT_DIRECTORY"

	// ServiceDataPrivacyUploadsStorageGcpBucketNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.DataPrivacy.Uploads.Storage.GCP.BucketName`.
	ServiceDataPrivacyUploadsStorageGcpBucketNameEnvVarKey = "ZHUZH_SERVICE_DATA_PRIVACY_UPLOADS_STORAGE_GCP_BUCKET_NAME"

	// ServiceDataPrivacyUploadsStorageProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.DataPrivacy.Uploads.Storage.Provider`.
	ServiceDataPrivacyUploadsStorageProviderEnvVarKey = "ZHUZH_SERVICE_DATA_PRIVACY_UPLOADS_STORAGE_PROVIDER"

	// ServiceDataPrivacyUploadsStorageS3BucketNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.DataPrivacy.Uploads.Storage.S3Config.BucketName`.
	ServiceDataPrivacyUploadsStorageS3BucketNameEnvVarKey = "ZHUZH_SERVICE_DATA_PRIVACY_UPLOADS_STORAGE_S3_BUCKET_NAME"

	// ServiceDataPrivacyUploadsStorageUploadFilenameKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.DataPrivacy.Uploads.Storage.UploadFilenameKey`.
	ServiceDataPrivacyUploadsStorageUploadFilenameKeyEnvVarKey = "ZHUZH_SERVICE_DATA_PRIVACY_UPLOADS_STORAGE_UPLOAD_FILENAME_KEY"

	// ServiceEnvironmentEnvVarKey is the environment variable name to set to override `EmailDeliverabilityTestConfigServiceEnvironment`.
	ServiceEnvironmentEnvVarKey = "ZHUZH_SERVICE_ENVIRONMENT"

	// ServiceOauth2ClientsCreationDisabledEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.OAuth2Clients.OAuth2ClientCreationDisabled`.
	ServiceOauth2ClientsCreationDisabledEnvVarKey = "ZHUZH_SERVICE_OAUTH2_CLIENTS_CREATION_DISABLED"

	// ServicePaymentsRevenuecatAPIKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Payments.RevenueCat.APIKey`.
	ServicePaymentsRevenuecatAPIKeyEnvVarKey = "ZHUZH_SERVICE_PAYMENTS_REVENUECAT_API_KEY"

	// ServicePaymentsRevenuecatWebhookAuthHeaderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Payments.RevenueCat.WebhookAuthHeader`.
	ServicePaymentsRevenuecatWebhookAuthHeaderEnvVarKey = "ZHUZH_SERVICE_PAYMENTS_REVENUECAT_WEBHOOK_AUTH_HEADER"

	// ServicePaymentsStripeAPIKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Payments.Stripe.APIKey`.
	ServicePaymentsStripeAPIKeyEnvVarKey = "ZHUZH_SERVICE_PAYMENTS_STRIPE_API_KEY"

	// ServicePaymentsStripeWebhookSecretEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Payments.Stripe.WebhookSecret`.
	ServicePaymentsStripeWebhookSecretEnvVarKey = "ZHUZH_SERVICE_PAYMENTS_STRIPE_WEBHOOK_SECRET"

	// ServiceUploadedMediaUploadsDebugEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.UploadedMedia.Uploads.Debug`.
	ServiceUploadedMediaUploadsDebugEnvVarKey = "ZHUZH_SERVICE_UPLOADED_MEDIA_UPLOADS_DEBUG"

	// ServiceUploadedMediaUploadsStorageBucketNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.UploadedMedia.Uploads.Storage.BucketName`.
	ServiceUploadedMediaUploadsStorageBucketNameEnvVarKey = "ZHUZH_SERVICE_UPLOADED_MEDIA_UPLOADS_STORAGE_BUCKET_NAME"

	// ServiceUploadedMediaUploadsStorageBucketPrefixEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.UploadedMedia.Uploads.Storage.BucketPrefix`.
	ServiceUploadedMediaUploadsStorageBucketPrefixEnvVarKey = "ZHUZH_SERVICE_UPLOADED_MEDIA_UPLOADS_STORAGE_BUCKET_PREFIX"

	// ServiceUploadedMediaUploadsStorageFilesystemRootDirectoryEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.UploadedMedia.Uploads.Storage.FilesystemConfig.RootDirectory`.
	ServiceUploadedMediaUploadsStorageFilesystemRootDirectoryEnvVarKey = "ZHUZH_SERVICE_UPLOADED_MEDIA_UPLOADS_STORAGE_FILESYSTEM_ROOT_DIRECTORY"

	// ServiceUploadedMediaUploadsStorageGcpBucketNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.UploadedMedia.Uploads.Storage.GCP.BucketName`.
	ServiceUploadedMediaUploadsStorageGcpBucketNameEnvVarKey = "ZHUZH_SERVICE_UPLOADED_MEDIA_UPLOADS_STORAGE_GCP_BUCKET_NAME"

	// ServiceUploadedMediaUploadsStorageProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.UploadedMedia.Uploads.Storage.Provider`.
	ServiceUploadedMediaUploadsStorageProviderEnvVarKey = "ZHUZH_SERVICE_UPLOADED_MEDIA_UPLOADS_STORAGE_PROVIDER"

	// ServiceUploadedMediaUploadsStorageS3BucketNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.UploadedMedia.Uploads.Storage.S3Config.BucketName`.
	ServiceUploadedMediaUploadsStorageS3BucketNameEnvVarKey = "ZHUZH_SERVICE_UPLOADED_MEDIA_UPLOADS_STORAGE_S3_BUCKET_NAME"

	// ServiceUploadedMediaUploadsStorageUploadFilenameKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.UploadedMedia.Uploads.Storage.UploadFilenameKey`.
	ServiceUploadedMediaUploadsStorageUploadFilenameKeyEnvVarKey = "ZHUZH_SERVICE_UPLOADED_MEDIA_UPLOADS_STORAGE_UPLOAD_FILENAME_KEY"

	// ServiceUsersPublicMediaURLPrefixEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Users.PublicMediaURLPrefix`.
	ServiceUsersPublicMediaURLPrefixEnvVarKey = "ZHUZH_SERVICE_USERS_PUBLIC_MEDIA_URL_PREFIX"

	// ServiceUsersUploadsDebugEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Users.Uploads.Debug`.
	ServiceUsersUploadsDebugEnvVarKey = "ZHUZH_SERVICE_USERS_UPLOADS_DEBUG"

	// ServiceUsersUploadsStorageBucketNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Users.Uploads.Storage.BucketName`.
	ServiceUsersUploadsStorageBucketNameEnvVarKey = "ZHUZH_SERVICE_USERS_UPLOADS_STORAGE_BUCKET_NAME"

	// ServiceUsersUploadsStorageBucketPrefixEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Users.Uploads.Storage.BucketPrefix`.
	ServiceUsersUploadsStorageBucketPrefixEnvVarKey = "ZHUZH_SERVICE_USERS_UPLOADS_STORAGE_BUCKET_PREFIX"

	// ServiceUsersUploadsStorageFilesystemRootDirectoryEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Users.Uploads.Storage.FilesystemConfig.RootDirectory`.
	ServiceUsersUploadsStorageFilesystemRootDirectoryEnvVarKey = "ZHUZH_SERVICE_USERS_UPLOADS_STORAGE_FILESYSTEM_ROOT_DIRECTORY"

	// ServiceUsersUploadsStorageGcpBucketNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Users.Uploads.Storage.GCP.BucketName`.
	ServiceUsersUploadsStorageGcpBucketNameEnvVarKey = "ZHUZH_SERVICE_USERS_UPLOADS_STORAGE_GCP_BUCKET_NAME"

	// ServiceUsersUploadsStorageProviderEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Users.Uploads.Storage.Provider`.
	ServiceUsersUploadsStorageProviderEnvVarKey = "ZHUZH_SERVICE_USERS_UPLOADS_STORAGE_PROVIDER"

	// ServiceUsersUploadsStorageS3BucketNameEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Users.Uploads.Storage.S3Config.BucketName`.
	ServiceUsersUploadsStorageS3BucketNameEnvVarKey = "ZHUZH_SERVICE_USERS_UPLOADS_STORAGE_S3_BUCKET_NAME"

	// ServiceUsersUploadsStorageUploadFilenameKeyEnvVarKey is the environment variable name to set to override `APIServiceConfig.Services.Users.Uploads.Storage.UploadFilenameKey`.
	ServiceUsersUploadsStorageUploadFilenameKeyEnvVarKey = "ZHUZH_SERVICE_USERS_UPLOADS_STORAGE_UPLOAD_FILENAME_KEY"

	// StorageBucketNameEnvVarKey is the environment variable name to set to override `AsyncMessageHandlerConfig.Storage.BucketName`.
	StorageBucketNameEnvVarKey = "ZHUZH_STORAGE_BUCKET_NAME"

	// StorageBucketPrefixEnvVarKey is the environment variable name to set to override `AsyncMessageHandlerConfig.Storage.BucketPrefix`.
	StorageBucketPrefixEnvVarKey = "ZHUZH_STORAGE_BUCKET_PREFIX"

	// StorageFilesystemRootDirectoryEnvVarKey is the environment variable name to set to override `AsyncMessageHandlerConfig.Storage.FilesystemConfig.RootDirectory`.
	StorageFilesystemRootDirectoryEnvVarKey = "ZHUZH_STORAGE_FILESYSTEM_ROOT_DIRECTORY"

	// StorageGcpBucketNameEnvVarKey is the environment variable name to set to override `AsyncMessageHandlerConfig.Storage.GCP.BucketName`.
	StorageGcpBucketNameEnvVarKey = "ZHUZH_STORAGE_GCP_BUCKET_NAME"

	// StorageProviderEnvVarKey is the environment variable name to set to override `AsyncMessageHandlerConfig.Storage.Provider`.
	StorageProviderEnvVarKey = "ZHUZH_STORAGE_PROVIDER"

	// StorageS3BucketNameEnvVarKey is the environment variable name to set to override `AsyncMessageHandlerConfig.Storage.S3Config.BucketName`.
	StorageS3BucketNameEnvVarKey = "ZHUZH_STORAGE_S3_BUCKET_NAME"

	// StorageUploadFilenameKeyEnvVarKey is the environment variable name to set to override `AsyncMessageHandlerConfig.Storage.UploadFilenameKey`.
	StorageUploadFilenameKeyEnvVarKey = "ZHUZH_STORAGE_UPLOAD_FILENAME_KEY"
)
