---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: prod
data:
  Caddyfile: |
    {
        acme_ca https://acme-v02.api.letsencrypt.org/directory
        acme_dns cloudflare {env.CLOUDFLARE_API_TOKEN}
    }

    api.zhuzh.dev {
        reverse_proxy zhuzh-api-svc.prod.svc.cluster.local:8001 {
            flush_interval -1
            transport http {
                versions h2c 2
            }
        }
    }

    http-api.zhuzh.dev {
        reverse_proxy zhuzh-api-svc.prod.svc.cluster.local:8000
    }

    admin.zhuzh.dev {
        reverse_proxy zhuzh-admin-webapp-svc.prod.svc.cluster.local:8888
    }

    zhuzh.dev, www.zhuzh.dev {
        reverse_proxy zhuzh-consumer-webapp-svc.prod.svc.cluster.local:80
    }

    mcp.zhuzh.dev {
        reverse_proxy zhuzh-mcp-server-svc.prod.svc.cluster.local:8888
    }
