---
apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: prod
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "api.zhuzh.dev,http-api.zhuzh.dev,admin.zhuzh.dev,zhuzh.dev,www.zhuzh.dev,mcp.zhuzh.dev"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  type: LoadBalancer
  selector:
    app: caddy
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
